"""
N-gram verbatim extraction attack.

THE headline metric for a synthetic-data paper: given the MTSamples training
corpus and a set of synthetic notes generated by our model, count how often
the synthetic notes contain k-grams that appear verbatim in the training set
but NOT in a large clean reference corpus.

This answers the question clinicians actually care about: "does my generator
leak real patient data into its synthetic outputs?"

Implementation notes
--------------------
- We use token-level n-grams (via the model's tokenizer), not whitespace
  words, so "Dr. Smith" and "Dr.Smith" aren't treated differently.
- We EXCLUDE n-grams that also appear in a large clean background corpus
  (e.g. PubMed or C4) to filter "medical boilerplate" matches like
  "no acute distress" that aren't real leakage.
- We report both EXACT-match rate (strong evidence of memorization) and
  MATCH-PER-NOTE (for distribution analysis).
"""

from __future__ import annotations

import argparse
import json
import logging
from collections import Counter
from pathlib import Path

import numpy as np
import yaml
from datasets import load_from_disk
from tqdm import tqdm
from transformers import AutoTokenizer


logging.basicConfig(level=logging.INFO, format="%(levelname)s | %(message)s")
log = logging.getLogger("attacks.extraction")


def tokens_to_ngrams(tokens: list[int], n: int) -> set[tuple[int, ...]]:
    if len(tokens) < n:
        return set()
    return {tuple(tokens[i : i + n]) for i in range(len(tokens) - n + 1)}


def build_ngram_index(
    dataset, tokenizer, n: int, max_length: int = 2048,
) -> Counter:
    """Build a counter of n-grams across a whole dataset."""
    counts = Counter()
    for row in tqdm(dataset, desc=f"indexing {n}-grams"):
        ids = tokenizer(
            row["text"], add_special_tokens=False, truncation=True, max_length=max_length,
        )["input_ids"]
        for ng in tokens_to_ngrams(ids, n):
            counts[ng] += 1
    return counts


def count_overlap_in_sample(
    text: str, tokenizer, n: int, training_set: set, exclusion_set: set | None,
    max_length: int = 2048,
) -> int:
    ids = tokenizer(
        text, add_special_tokens=False, truncation=True, max_length=max_length,
    )["input_ids"]
    ngrams = tokens_to_ngrams(ids, n)
    if exclusion_set is not None:
        # only count n-grams that are in the training set but not in the background
        hits = ngrams & training_set - exclusion_set
    else:
        hits = ngrams & training_set
    return len(hits)


def run_extraction(cfg: dict):
    splits = load_from_disk(cfg["splits_path"])
    tokenizer = AutoTokenizer.from_pretrained(cfg["tokenizer"])

    log.info("building n-gram index for training set (members)")
    train_idx = build_ngram_index(
        splits["members"], tokenizer, cfg["n"], cfg.get("max_length", 2048),
    )
    training_set = set(train_idx.keys())
    log.info("training set has %d unique %d-grams", len(training_set), cfg["n"])

    exclusion_set = None
    if cfg.get("background_path"):
        log.info("building exclusion index from background corpus")
        # background corpus format: JSONL with a "text" field
        from datasets import Dataset
        bg = []
        with open(cfg["background_path"]) as f:
            for line in f:
                bg.append(json.loads(line))
        bg_ds = Dataset.from_list(bg)
        bg_idx = build_ngram_index(
            bg_ds, tokenizer, cfg["n"], cfg.get("max_length", 2048),
        )
        exclusion_set = set(bg_idx.keys())
        log.info("exclusion set has %d unique %d-grams", len(exclusion_set), cfg["n"])
        # Remaining "sensitive" n-grams = in training, not in background
        sensitive = training_set - exclusion_set
        log.info("sensitive n-grams: %d (%.2f%% of training)",
                 len(sensitive), 100 * len(sensitive) / max(len(training_set), 1))

    # --- Score synthetic corpus ---
    log.info("scoring synthetic corpus %s", cfg["synthetic_path"])
    per_sample_counts = []
    samples_with_hits = 0
    total_hits = 0

    with open(cfg["synthetic_path"]) as f:
        for line in tqdm(f, desc="synth"):
            rec = json.loads(line)
            hits = count_overlap_in_sample(
                rec["text"], tokenizer, cfg["n"], training_set, exclusion_set,
                cfg.get("max_length", 2048),
            )
            per_sample_counts.append(hits)
            total_hits += hits
            if hits > 0:
                samples_with_hits += 1

    counts = np.array(per_sample_counts, dtype=np.int64)
    n_samples = len(counts)
    summary = {
        "n": cfg["n"],
        "n_samples": n_samples,
        "n_samples_with_hits": samples_with_hits,
        "frac_samples_with_hits": samples_with_hits / max(n_samples, 1),
        "total_hits": int(total_hits),
        "mean_hits_per_sample": float(counts.mean()) if n_samples else 0.0,
        "max_hits_in_a_sample": int(counts.max()) if n_samples else 0,
        "percentile_95_hits": float(np.percentile(counts, 95)) if n_samples else 0.0,
    }

    out_dir = Path(cfg["output_dir"])
    out_dir.mkdir(parents=True, exist_ok=True)
    with open(out_dir / f"extraction_n{cfg['n']}.json", "w") as f:
        json.dump(summary, f, indent=2)

    log.info("\n=== Extraction summary (n=%d) ===", cfg["n"])
    for k, v in summary.items():
        log.info("  %-28s %s", k, v)

    return summary


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--config", required=True)
    ap.add_argument("--synthetic_path_override", default=None)
    ap.add_argument("--output_dir_override", default=None)
    args = ap.parse_args()

    with open(args.config) as f:
        cfg = yaml.safe_load(f)
    if args.synthetic_path_override:
        cfg["synthetic_path"] = args.synthetic_path_override
    if args.output_dir_override:
        cfg["output_dir"] = args.output_dir_override

    # Run at multiple n values to characterize the leakage distribution
    ns = cfg.get("n_list", [25, 50, 100])
    for n in ns:
        cfg_n = dict(cfg)
        cfg_n["n"] = n
        run_extraction(cfg_n)


if __name__ == "__main__":
    main()
