"""
Data preparation for the MTSamples unlearning + DP experiment.

Key design decisions:

1. MTSamples has ~5000 transcribed notes. We split into:
   - FORGET / MEMBERS (the fine-tuning set, also presumed in pre-training):
     these are the notes we will both (a) unlearn from the base model and
     (b) fine-tune on with DP. Same set for both, because the research question
     is about restoring DP guarantees on pre-training-contaminated data.
   - NONMEMBERS (evaluation-only): held out, never seen by fine-tuning.
     These are used as the "out" population for MIA evaluation. They may
     still be in pre-training (if from MTSamples), so we ALSO maintain...
   - NONMEMBERS_CLEAN: a held-out set sourced from a dataset that is
     demonstrably NOT in pre-training (e.g., synthetic notes generated by
     a different pipeline, or a dated post-cutoff clinical corpus).
   - RETAIN: in-distribution clinical text used by GA+GD unlearning as the
     gradient descent target. Sourced from PubMed abstracts or a different
     clinical corpus — NOT from MTSamples, and NOT from our MEMBERS set.

2. Canaries: we inject a small number (~100) of synthetic canary sequences
   into the fine-tuning set. These let us compute empirical DP bounds per
   Panda et al. 2025 ("Privacy Auditing of Large Language Models"). Canaries
   are designed to be memorization-prone (high-entropy, outlier phrases).

3. All splits are determined by a fixed seed so reruns are reproducible.
"""

from __future__ import annotations

import hashlib
import json
import random
import string
from dataclasses import dataclass, asdict
from pathlib import Path
from typing import Literal

import yaml
from datasets import Dataset, DatasetDict


@dataclass
class SplitConfig:
    mtsamples_path: str                  # path to raw MTSamples CSV/JSONL
    retain_corpus_path: str              # path to retain corpus (e.g. PubMed)
    clean_nonmember_path: str            # path to post-cutoff / synthetic nonmembers
    out_dir: str

    n_members: int = 2000                # fine-tuning set size (will also be "forget" set)
    n_nonmembers: int = 1000             # from MTSamples, held out
    n_clean_nonmembers: int = 1000       # from a pre-training-free source
    n_retain: int = 2000                 # for GA+GD unlearning

    n_canaries: int = 100                # DP audit canaries
    canary_length: int = 40              # tokens; long enough to be distinctive
    canary_seed: int = 1337

    seed: int = 42
    min_note_tokens: int = 128           # filter notes shorter than this
    max_note_tokens: int = 1024          # truncate longer notes


def _doc_hash(text: str) -> str:
    """Stable document ID independent of order."""
    return hashlib.sha256(text.encode("utf-8")).hexdigest()[:16]


def _generate_canary(rng: random.Random, length: int) -> dict:
    """
    Generate a DP-audit canary: a high-entropy string that a memorization-prone
    model will fit easily, but a non-memorizing model should be uncertain about.

    Design follows Panda et al. 2025: canaries should live in the model's input
    distribution (so they are plausible) but be unique enough that verbatim
    extraction is unambiguous evidence of membership.

    We produce a medical-flavored canary: plausible-sounding but fake patient/ID
    tokens that the model has no prior on.
    """
    # Medical-flavored filler so the canary isn't obviously out of distribution
    templates = [
        "Patient {pid} presented on {date} with complaint of {symptom}. "
        "Attending {doctor} noted {finding}. Disposition: {disposition}. Code {code}.",
        "Chart {pid} dated {date}. Chief complaint: {symptom}. "
        "Provider {doctor}. Impression: {finding}. Plan: {disposition}. Ref {code}.",
    ]
    rand_id = lambda n: "".join(rng.choices(string.ascii_uppercase + string.digits, k=n))
    vals = {
        "pid": rand_id(8),
        "date": f"{rng.randint(2019, 2023)}-{rng.randint(1,12):02d}-{rng.randint(1,28):02d}",
        "symptom": rng.choice([
            "xanthine-induced myalgia", "unspecified costochondral pain",
            "transient vestibular drift", "atypical periorbital flushing",
        ]),
        "doctor": f"Dr. {rand_id(6).title()}",
        "finding": rng.choice([
            "unremarkable serology with mild elevation",
            "stable imaging; no acute intervention",
            "chronic nonspecific findings, reassured",
        ]),
        "disposition": rng.choice(["home with follow-up", "observation", "consult pending"]),
        "code": rand_id(10),
    }
    text = rng.choice(templates).format(**vals)
    # Pad or trim to approximately `length` tokens (rough: 1 token ≈ 0.75 words)
    words = text.split()
    target_words = max(length, int(length * 1.3))
    while len(words) < target_words:
        words.append(rand_id(rng.randint(4, 8)))
    text = " ".join(words[:target_words])
    return {
        "text": text,
        "doc_id": _doc_hash(text),
        "is_canary": True,
    }


def load_mtsamples(path: str) -> list[dict]:
    """
    Load MTSamples. Expected format: JSONL with {"text": ..., "specialty": ...}
    Adapt this function to your actual MTSamples dump.
    """
    path = Path(path)
    records = []
    if path.suffix == ".jsonl":
        with open(path) as f:
            for line in f:
                records.append(json.loads(line))
    elif path.suffix == ".csv":
        import pandas as pd
        df = pd.read_csv(path)
        # MTSamples CSV typically has columns: description, medical_specialty, transcription
        for _, row in df.iterrows():
            text = str(row.get("transcription", "")).strip()
            if text:
                records.append({
                    "text": text,
                    "specialty": row.get("medical_specialty", "unknown"),
                })
    else:
        raise ValueError(f"unsupported MTSamples format: {path.suffix}")
    return records


def load_text_corpus(path: str) -> list[dict]:
    """Generic loader for retain corpus or clean-nonmember corpus."""
    path = Path(path)
    records = []
    if path.suffix == ".jsonl":
        with open(path) as f:
            for line in f:
                records.append(json.loads(line))
    elif path.suffix == ".txt":
        # one document per blank-line-separated block
        text = path.read_text()
        for chunk in text.split("\n\n"):
            chunk = chunk.strip()
            if chunk:
                records.append({"text": chunk})
    else:
        raise ValueError(f"unsupported corpus format: {path.suffix}")
    return records


def _filter_by_length(records: list[dict], tokenizer, min_tok: int, max_tok: int) -> list[dict]:
    """Filter by approximate token length using the actual tokenizer."""
    out = []
    for r in records:
        toks = tokenizer(r["text"], add_special_tokens=False)["input_ids"]
        if len(toks) < min_tok:
            continue
        # truncate rather than drop; keep the head
        if len(toks) > max_tok:
            r = dict(r)
            r["text"] = tokenizer.decode(toks[:max_tok], skip_special_tokens=True)
        out.append(r)
    return out


def build_splits(cfg: SplitConfig, tokenizer) -> DatasetDict:
    """Produce the full DatasetDict of member / nonmember / retain / canary splits."""
    rng = random.Random(cfg.seed)

    # --- MTSamples: members + nonmembers ---
    mts = load_mtsamples(cfg.mtsamples_path)
    mts = _filter_by_length(mts, tokenizer, cfg.min_note_tokens, cfg.max_note_tokens)
    rng.shuffle(mts)

    need = cfg.n_members + cfg.n_nonmembers
    if len(mts) < need:
        raise ValueError(
            f"MTSamples has {len(mts)} valid notes after filtering; "
            f"need {need} for requested member+nonmember split"
        )
    members = mts[: cfg.n_members]
    nonmembers = mts[cfg.n_members : cfg.n_members + cfg.n_nonmembers]

    # Add stable IDs and split labels
    for r in members:
        r["doc_id"] = _doc_hash(r["text"])
        r["split"] = "member"
        r["is_canary"] = False
    for r in nonmembers:
        r["doc_id"] = _doc_hash(r["text"])
        r["split"] = "nonmember"
        r["is_canary"] = False

    # --- Clean nonmembers (for separating pre-training contamination from FT contamination) ---
    clean = load_text_corpus(cfg.clean_nonmember_path)
    clean = _filter_by_length(clean, tokenizer, cfg.min_note_tokens, cfg.max_note_tokens)
    rng.shuffle(clean)
    if len(clean) < cfg.n_clean_nonmembers:
        raise ValueError(f"clean nonmember corpus too small: {len(clean)}")
    clean_nm = clean[: cfg.n_clean_nonmembers]
    for r in clean_nm:
        r["doc_id"] = _doc_hash(r["text"])
        r["split"] = "clean_nonmember"
        r["is_canary"] = False

    # --- Retain set for GA+GD unlearning ---
    retain = load_text_corpus(cfg.retain_corpus_path)
    retain = _filter_by_length(retain, tokenizer, cfg.min_note_tokens, cfg.max_note_tokens)
    rng.shuffle(retain)
    if len(retain) < cfg.n_retain:
        raise ValueError(f"retain corpus too small: {len(retain)}")
    retain = retain[: cfg.n_retain]
    for r in retain:
        r["doc_id"] = _doc_hash(r["text"])
        r["split"] = "retain"
        r["is_canary"] = False

    # --- Canaries (injected into the member/fine-tuning set only) ---
    canary_rng = random.Random(cfg.canary_seed)
    canaries = [
        _generate_canary(canary_rng, cfg.canary_length) for _ in range(cfg.n_canaries)
    ]
    for c in canaries:
        c["split"] = "canary"
        c["specialty"] = "canary"

    # Fine-tuning set = members + canaries (canaries are members too, just flagged)
    ft_set = members + canaries

    splits = DatasetDict({
        "finetune": Dataset.from_list(ft_set),           # what DP fine-tuning sees
        "members": Dataset.from_list(members),            # for MIA "in" population
        "nonmembers": Dataset.from_list(nonmembers),      # for MIA "out" population (same-distribution)
        "clean_nonmembers": Dataset.from_list(clean_nm),  # for MIA "out" with known non-contamination
        "retain": Dataset.from_list(retain),              # for GA+GD unlearning descent term
        "canaries": Dataset.from_list(canaries),          # for DP audit
    })

    out_dir = Path(cfg.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    splits.save_to_disk(str(out_dir))

    # Save config alongside for provenance
    with open(out_dir / "split_config.yaml", "w") as f:
        yaml.safe_dump(asdict(cfg), f)

    # Save a summary so it's easy to sanity-check
    summary = {name: len(ds) for name, ds in splits.items()}
    with open(out_dir / "summary.json", "w") as f:
        json.dump(summary, f, indent=2)

    return splits


def main():
    import argparse
    from transformers import AutoTokenizer

    ap = argparse.ArgumentParser()
    ap.add_argument("--config", required=True, help="path to data split YAML config")
    ap.add_argument("--tokenizer", default="meta-llama/Meta-Llama-3-8B")
    args = ap.parse_args()

    with open(args.config) as f:
        cfg_dict = yaml.safe_load(f)
    cfg = SplitConfig(**cfg_dict)

    tokenizer = AutoTokenizer.from_pretrained(args.tokenizer)
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token

    splits = build_splits(cfg, tokenizer)
    print("Splits saved to", cfg.out_dir)
    for name, ds in splits.items():
        print(f"  {name}: {len(ds)}")


if __name__ == "__main__":
    main()
