base_model: /fs1/shared/model/llm/Llama-3.1-8B-Instruct
max_examples: 500
max_length: 512
output_dir: /fs1/projects/unlearning_pretraining/Proj_code/Scripts_3.0/New Experiment/Unlearning/mtsamples_unlearn_dp/mtsamples_unlearn_dp/outputs/attacks/compl_baseline_nonmem_pmc
prefix_ratio: 0.5
splits_path: /fs1/projects/unlearning_pretraining/Proj_code/Scripts_3.0/New Experiment/Unlearning/mtsamples_unlearn_dp/mtsamples_unlearn_dp/outputs/splits_v1_pmc
